language: cpp

os:
  - linux
  - osx

install:
  - mkdir -p ~/neko
  - curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz' | tar -C ~/neko -x -z --strip-components=1 -f -
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/neko"
  - export PATH="${PATH}:${HOME}/neko"
  - mkdir -p ~/haxe
  - curl -s -L --retry 3 'http://haxe.org/website-content/downloads/3,1,3/downloads/haxe-3.1.3-linux64.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -
  - export PATH="${PATH}:${HOME}/haxe"
  - export HAXE_STD_PATH="${HOME}/haxe/std"
  - mkdir -p ~/haxe/lib
  - haxelib setup ~/haxe/lib
  - echo $(haxe -version)
  - echo $(neko -version)
  - haxelib install hxcpp
  - make
  - mv ndll/Linux64/hxssl.ndll ~/neko/

script:
  - cd test
  - haxe build-neko.hxml
  - neko test
  - haxe build-cpp.hxml
  - ./Run

notifications:
  email: false