language: haxe

haxe: development

sudo: false
addons:
  apt:
    packages: &apt_common
      - gcc-multilib

matrix:
  include:
    - os: linux
    - os: osx

script:
  # Remove all ndll - we want to build them from source
  - rm -rf ndll
  - haxelib install hxcpp
  - make
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mv ndll/Linux64/hxssl.ndll ~/neko/;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      mv ndll/Mac64/hxssl.ndll ~/neko/;
    fi
  - cd test
  # Build neko binary and test
  - haxe build-neko.hxml
  - neko test
  # Build cpp binary and test
  - haxe build-cpp.hxml
  - ./Run

notifications:
  email: false