language: generic

sudo: false
addons:
  apt:
    packages: &apt_common
      - zlib1g-dev
      - libgc-dev

matrix:
  include:
    - os: linux
    - os: osx

install:
  # Install haxe and neko dependencies
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    travis_retry brew update;
    travis_retry brew install caskroom/cask/brew-cask;
    fi
  # Install neko
  - mkdir -p ~/neko
  - curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz' | tar -C ~/neko -x -z --strip-components=1 -f -
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/neko"
  - export PATH="${PATH}:${HOME}/neko"
  # Install haxe
  - mkdir -p ~/haxe
  - curl -s -L --retry 3 'http://haxe.org/website-content/downloads/3.2.0/downloads/haxe-3.2.0-linux64.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -
  - export PATH="${PATH}:${HOME}/haxe"
  - export HAXE_STD_PATH="${HOME}/haxe/std"
  - mkdir -p ~/haxe/lib
  - haxelib setup ~/haxe/lib
  - echo $(haxe -version)
  - echo $(neko -version)
  - haxelib install hxcpp
  - make
  - mv ndll/Linux64/hxssl.ndll ~/neko/

script:
  - cd test
  - haxe build-neko.hxml
  - neko test
  - haxe build-cpp.hxml
  - ./Run

notifications:
  email: false