language: haxe

sudo: false

matrix:
  include:
    - os: linux
    - os: osx

script:
  - cd test
  - haxe build-neko.hxml
  - neko test
  - haxe build-cpp.hxml
  - ./Run

notifications:
  email: false