language: haxe

sudo: false

matrix:
  include:
    - os: linux
    - os: osx

script:
  - haxelib install hxcpp
  - make
  - mv ndll/Linux64/hxssl.ndll ~/neko/
  - cd test
  - haxe build-neko.hxml
  - neko test
  - haxe build-cpp.hxml
  - ./Run

notifications:
  email: false